streamx.blueprints.data-collector.web-resources.filters=collected_.*
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.data-key-match-pattern=product:.*
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.collector=aggregate-by-property-value
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.outputkeyprefix=collected_products_cheapest-by-category_
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.groupby=categories/name
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.sortby=price/value
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.sortmode=asc
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.max=8

streamx.blueprints.data-collector.configurations.featured-by-category.data-key-match-pattern=product:.*
streamx.blueprints.data-collector.configurations.featured-by-category.collector=aggregate-by-property-value
streamx.blueprints.data-collector.configurations.featured-by-category.properties.outputkeyprefix=collected_products_featured-by-category_
streamx.blueprints.data-collector.configurations.featured-by-category.properties.groupby=categories/name
streamx.blueprints.data-collector.configurations.featured-by-category.properties.max=8
streamx.blueprints.data-collector.configurations.featured-by-category.properties.filterby=$.categories[?(@.name == 'Featured')]

streamx.blueprints.data-collector.configurations.filtered-by-quantity.data-key-match-pattern=product:.*
streamx.blueprints.data-collector.configurations.filtered-by-quantity.collector=aggregate-by-property-value
streamx.blueprints.data-collector.configurations.filtered-by-quantity.properties.outputkeyprefix=collected_products_min_ten_cheapest-by-category_
streamx.blueprints.data-collector.configurations.filtered-by-quantity.properties.groupby=categories/name
streamx.blueprints.data-collector.configurations.filtered-by-quantity.properties.sortby=price/value
streamx.blueprints.data-collector.configurations.filtered-by-quantity.properties.sortmode=asc
streamx.blueprints.data-collector.configurations.filtered-by-quantity.properties.max=8
streamx.blueprints.data-collector.configurations.filtered-by-quantity.properties..filterby=$[?(@.quantity > '10')]

