streamx.blueprints.external-references-rewriter.base-url-for-relative-paths=https://main--demo-puresight-eds-next--streamx-dev.aem.live/
streamx.blueprints.external-references-rewriter.processable-payload-types=web-resource/static
streamx.blueprints.external-references-rewriter.html-external-resource-xpath-selectors=//img/@src,//picture/source/@srcset
streamx.blueprints.external-references-rewriter.json-external-resource-jsonpath-selectors=$.data[*].img,$.data[*].avatar
streamx.blueprints.external-references-rewriter.emitted-page-type=page/external
streamx.blueprints.external-references-rewriter.emitted-web-resource-type=web-resource/external
streamx.blueprints.external-references-rewriter.emitted-asset-type=asset/external