# Docker internal DNS server
resolver 127.0.0.11;

server {
    listen 80;
    root   /usr/share/nginx/html;
    index  homepage.html;

    location / {
        try_files $uri $uri/ @html;
    }

    location @html {
        rewrite ^(.*)$ $1.html break;
    }

    error_page 404 /errors/404.html;
    location /errors {
        internal;
    }

    location ~ \.html$ {
        ssi on;
    }

    location /favicon.ico {
        try_files $uri /assets/static/favicon.ico =404;
    }

    location /health {
        access_log off;
        add_header  Content-Type    text/html;
        return 200;
    }

}
