---
domains: []
global:
  services:
    ingestion:
      rest-ingestion:
        replicas: 1
    processing:
      pages-optimized-img-rewriter:
        stateful: true
      json-aggregator:
        stateful: true
      rendering-engine:
        stateful: true
      composition-engine:
        stateful: true
      data-collector:
        stateful: true
      sitemap-generator:
        stateful: true
    edge:
      search-sink:
        replicas: 1
        stateful: true
      web-server-sink:
        replicas: 1
        stateful: true
      openai-rag-sink:
        replicas: 1
        stateful: true
  properties: {}
clusters:
  eu-west-gra-processing:
    enabled: true
    overlay:
      properties: {}
  eu-west-gra-edge:
    enabled: true
    overlay:
      properties: {}
  ca-east-bhs-edge:
    enabled: true
    overlay:
      properties: {}
  us-east-chi-edge:
    enabled: true
    overlay:
      properties: {}
